# .travis.yml
language: python

env:
  - LUA="lua=5.1.5"
before_install:
  - sudo ./install-dev.sh

install:
  - pip install openwisp-utils[qa]>=0.7

script:
  - openwisp-qa-check --skip-checkmigrations --skip-isort --skip-flake8 --skip-black
  - ./runtests

notifications:
  # will post a summary as comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
